### ISSUE TITLE
"Failed to load RPC schema" because imported files are not identified

### ISSUE THREAD

**Issue by jskelcy** [rogchap/wombat#20]
Hello,

This is a really neat project and very excited to get it working and introduce it to my team. I am messing around with it and having a little bit of trouble.

I have a `Root` file that defines my service, which I am importing. I have also had wombat traverse my Proto Source files which include some shared objects which are imported in multiple service definitions. 

However when I try to `Connect` I get the following error (some stuff is redacted):
<img width="475" alt="Screen Shot 2020-11-13 at 10 23 40 AM" src="https://user-images.githubusercontent.com/2659770/99088900-a2b69c80-259a-11eb-8ebc-c8838f5f60eb.png">

Now my service definition includes importing the file in question like this:
`import "idl/shared/common/common.proto";`

It sort of seems like it is looking for an import to be defined as an absolute path rather than the relative path? I am not sure what are the next steps here, it seems like I might just be misunderstanding how to set up a workspace. Let me know if anything seems obviously wrong.

**Comment by rogchap** [comment]
All paths entered into Wombat are Absolute Paths (because Wombat is normally running in your Applications directory, not at the root of your proto directory).

Because of this you need to tell Wombat what is the root (import) path for your protos.

It seems that your import path needs to be set to `/User/jxxxxxx/codxxxxx/` so that when Wombat parses `import "idl/shared/common/common.proto";` it knows to try and find that file under `/User/jxxxxxx/codxxxxx/idl/shared/common/common.proto`

In my example you can see I need to define two root paths:

![image](https://user-images.githubusercontent.com/270252/99124808-fbe40600-2656-11eb-9a00-3153cd800896.png)
